'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import type {User} from '@supabase/supabase-js';
import {supabase} from '../../lib/supabase-browser';
import {destinations,newTrip,planOutfits,shops,validInspiration,type ClosetItem,type DestinationName,type Trip,type TripDetails} from '../../lib/trip';
import './style.css';

const categories:ClosetItem['category'][]=['Top','Bottom','Dress','Layer','Shoes','Accessory'];
const activities=['Sightseeing','Beach','Dining','Nightlife','Work','Hiking'];
function App(){
  const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[trips,setTrips]=useState<Trip[]>([]),[active,setActive]=useState<Trip|null>(null);
  const [mode,setMode]=useState<'signin'|'signup'>('signup'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const [draft,setDraft]=useState<TripDetails>(newTrip),[title,setTitle]=useState('My next trip'),[tab,setTab]=useState<'plan'|'outfits'|'packing'|'inspo'|'shop'>('plan');
  const [itemName,setItemName]=useState(''),[itemCategory,setItemCategory]=useState<ClosetItem['category']>('Top'),[link,setLink]=useState('');
  useEffect(()=>{let live=true;supabase.auth.getUser().then(({data})=>{if(live){setUser(data.user);setLoading(false)}});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{setUser(session?.user||null);if(!session?.user){setTrips([]);setActive(null)}});return()=>{live=false;subscription.unsubscribe()}},[]);
  useEffect(()=>{if(!user)return;let live=true;supabase.from('trips').select('id,title,details,created_at,updated_at').order('updated_at',{ascending:false}).then(({data,error})=>{if(!live)return;if(error)setMessage(error.message);else setTrips((data||[]) as Trip[])});return()=>{live=false}},[user]);
  function selectTrip(trip:Trip){setActive(trip);setDraft(trip.details);setTitle(trip.title);setTab('plan');setMessage('')}
  function startTrip(){setActive(null);setDraft(newTrip());setTitle('My next trip');setTab('plan');setMessage('')}
  async function authSubmit(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage('');const result=mode==='signup'?await supabase.auth.signUp({email,password,options:{emailRedirectTo:`${location.origin}/app`}}):await supabase.auth.signInWithPassword({email,password});setBusy(false);if(result.error)setMessage(result.error.message);else if(mode==='signup'&&!result.data.session)setMessage('Check your email to confirm your account, then sign in.');else setMessage('Welcome to FitForTrip. ✦')}
  async function save(){if(!user)return;if(!title.trim()){setMessage('Give your trip a name.');return}if(draft.stops.some(s=>s.start&&s.end&&s.end<s.start)){setMessage('Each stop needs an end date after its start date.');return}setBusy(true);setMessage('');const payload={title:title.trim(),details:draft,user_id:user.id,updated_at:new Date().toISOString()};const result=active?await supabase.from('trips').update(payload).eq('id',active.id).select('id,title,details,created_at,updated_at').single():await supabase.from('trips').insert(payload).select('id,title,details,created_at,updated_at').single();setBusy(false);if(result.error){setMessage(result.error.message);return}const saved=result.data as Trip;setActive(saved);setTrips(old=>[saved,...old.filter(t=>t.id!==saved.id)]);setMessage('Trip saved. ✦')}
  async function removeTrip(){if(!active||!confirm(`Delete “${active.title}”?`))return;const {error}=await supabase.from('trips').delete().eq('id',active.id);if(error){setMessage(error.message);return}setTrips(old=>old.filter(t=>t.id!==active.id));startTrip();setMessage('Trip deleted.')}
  function change(patch:Partial<TripDetails>){setDraft(old=>({...old,...patch}));setMessage('')}
  if(loading)return <main className="fft-app fft-center">Opening your suitcase…</main>;
  return <main className="fft-app"><header className="fft-header"><Link href="/" className="fft-logo">FitForTrip <span>✦</span></Link><div className="fft-header-right"><span>Look good. Go places.</span>{user&&<button className="fft-text-button" onClick={()=>supabase.auth.signOut()}>Sign out</button>}</div></header>
    {!user?<section className="fft-auth"><div className="fft-auth-art"><span className="fft-kicker">YOUR TRIP, YOUR STYLE</span><h1>Pack for the<br/><em>life you’ll live there.</em></h1><p>Build a trip across cities, make looks from your own wardrobe, collect inspiration, and leave with a packing list that makes sense.</p><div className="fft-stamps"><span>01 Plan</span><span>02 Style</span><span>03 Go</span></div></div><form className="fft-auth-card" onSubmit={authSubmit}><span className="fft-kicker">WELCOME TO FITFORTRIP</span><h2>{mode==='signup'?'Make room for a better trip.':'Welcome back.'}</h2><p>{mode==='signup'?'Create your free account to save your plans.':'Sign in to pick up where you left off.'}</p><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<input type="password" minLength={6} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 6 characters"/></label><button className="fft-primary" disabled={busy}>{busy?'One moment…':mode==='signup'?'Create account':'Sign in'} <span>↗</span></button><button type="button" className="fft-switch" onClick={()=>{setMode(mode==='signup'?'signin':'signup');setMessage('')}}>{mode==='signup'?'Already have an account? Sign in':'New here? Create an account'}</button><p role="status" className="fft-message">{message}</p></form></section>:
    <div className="fft-shell"><aside className="fft-sidebar"><div className="fft-side-top"><span className="fft-kicker">YOUR SUITCASE</span><h2>My trips <span>✦</span></h2><button className="fft-primary" onClick={startTrip}>+ New trip</button></div><div className="fft-trip-list">{trips.map(t=><button key={t.id} className={'fft-trip-card '+(active?.id===t.id?'selected':'')} onClick={()=>selectTrip(t)}><strong>{t.title}</strong><small>{t.details?.stops?.map(s=>s.destination).join(' · ')||'Your next escape'}</small></button>)}{!trips.length&&<p className="fft-muted">Your first trip starts here.</p>}</div><div className="fft-side-foot">A little less packing panic.<br/>A lot more you. ♡</div></aside>
    <section className="fft-workspace"><div className="fft-workspace-head"><div><span className="fft-kicker">{active?'TRIP STUDIO':'LET’S GO SOMEWHERE'}</span><h1>{active?'Your trip, styled.':'Plan your next escape.'}</h1></div><div className="fft-actions">{active&&<button className="fft-text-button" onClick={removeTrip}>Delete</button>}<button className="fft-primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save trip'} <span>↗</span></button></div></div><div className="fft-tabs" role="tablist">{(['plan','outfits','packing','inspo','shop'] as const).map(t=><button key={t} role="tab" aria-selected={tab===t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{({plan:'Trip plan',outfits:'Outfits',packing:'Packing',inspo:'Inspiration',shop:'Shop'} as const)[t]}</button>)}</div><p role="status" className="fft-message">{message}</p>
    {tab==='plan'&&<div className="fft-grid"><section className="fft-panel"><span className="fft-kicker">01 / THE ITINERARY</span><h2>Where are we going?</h2><label>Trip name<input value={title} maxLength={120} onChange={e=>setTitle(e.target.value)} placeholder="My next trip"/></label><div className="fft-stop-list">{draft.stops.map((stop,index)=><div className="fft-stop" key={stop.id}><div className="fft-stop-title"><strong>Stop {String(index+1).padStart(2,'0')}</strong>{draft.stops.length>1&&<button className="fft-text-button" onClick={()=>change({stops:draft.stops.filter(s=>s.id!==stop.id)})}>Remove</button>}</div><label>Destination<select value={stop.destination} onChange={e=>change({stops:draft.stops.map(s=>s.id===stop.id?{...s,destination:e.target.value as DestinationName}:s)})}>{destinations.map(d=><option key={d.name} value={d.name}>{d.name}, {d.country}</option>)}</select></label><div className="fft-two"><label>From<input type="date" value={stop.start} onChange={e=>change({stops:draft.stops.map(s=>s.id===stop.id?{...s,start:e.target.value}:s)})}/></label><label>To<input type="date" min={stop.start||undefined} value={stop.end} onChange={e=>change({stops:draft.stops.map(s=>s.id===stop.id?{...s,end:e.target.value}:s)})}/></label></div><p className="fft-hint">{destinations.find(d=>d.name===stop.destination)?.tip}</p></div>)}</div><button className="fft-outline" onClick={()=>change({stops:[...draft.stops,{id:crypto.randomUUID(),destination:'Paris',start:'',end:''}]})}>+ Add another stop</button></section><section className="fft-panel"><span className="fft-kicker">02 / YOUR VIBE</span><h2>Make it yours.</h2><label>Describe your style<input value={draft.style} onChange={e=>change({style:e.target.value})} placeholder="Easy chic, colourful, minimal…"/></label><label>What are you doing?</label><div className="fft-chips">{activities.map(a=><button className={draft.activities.includes(a)?'active':''} key={a} onClick={()=>change({activities:draft.activities.includes(a)?draft.activities.filter(v=>v!==a):[...draft.activities,a]})}>{a}</button>)}</div><label>Trip notes<textarea value={draft.notes} onChange={e=>change({notes:e.target.value})} placeholder="Dress code, special events, or anything you don't want to forget" rows={4}/></label><div className="fft-info"><strong>Planning note</strong><p>Outfit suggestions use your itinerary and wardrobe. Destination tips are general seasonal guidance, not a live weather forecast. Check the forecast before you pack.</p></div></section></div>}
    {tab==='outfits'&&<div className="fft-grid"><section className="fft-panel"><span className="fft-kicker">03 / YOUR CLOSET</span><h2>Start with what you own.</h2><p>Add the pieces you might bring. We’ll use them in your outfit plan.</p><div className="fft-add-row"><input aria-label="Clothing item" value={itemName} onChange={e=>setItemName(e.target.value)} placeholder="White linen shirt"/><select aria-label="Category" value={itemCategory} onChange={e=>setItemCategory(e.target.value as ClosetItem['category'])}>{categories.map(c=><option key={c}>{c}</option>)}</select><button onClick={()=>{if(itemName.trim()){change({closet:[...draft.closet,{id:crypto.randomUUID(),name:itemName.trim(),category:itemCategory}]});setItemName('')}}}>Add</button></div><div className="fft-item-list">{draft.closet.map(item=><div key={item.id}><span><small>{item.category}</small>{item.name}</span><button aria-label={`Remove ${item.name}`} onClick={()=>change({closet:draft.closet.filter(v=>v.id!==item.id)})}>×</button></div>)}{!draft.closet.length&&<p className="fft-muted">Your wardrobe is a blank canvas. Add a few favourite pieces.</p>}</div></section><section className="fft-panel"><span className="fft-kicker">04 / THE LOOKS</span><h2>Outfits for every stop.</h2><p>Generate a starting plan, then edit each outfit to make it yours.</p><button className="fft-primary" onClick={()=>{change({outfits:planOutfits(draft)});setMessage('Outfit plan created. Save your trip to keep it.')}}>Generate outfits ✦</button><div className="fft-outfits">{draft.outfits.map((o,i)=><div className="fft-outfit" key={o.id}><small>LOOK {String(i+1).padStart(2,'0')}</small><strong>{o.label}</strong><textarea aria-label={`Items for ${o.label}`} value={o.items.join('\n')} rows={3} onChange={e=>change({outfits:draft.outfits.map(v=>v.id===o.id?{...v,items:e.target.value.split('\n')}:v)})}/></div>)}{!draft.outfits.length&&<div className="fft-empty">Your outfits will appear here. ✳</div>}</div></section></div>}
    {tab==='packing'&&<div className="fft-panel fft-wide"><span className="fft-kicker">05 / READY TO GO</span><h2>Your packing list.</h2><p>Check off your outfits as they go into your suitcase. Individual wardrobe pieces are listed below.</p><div className="fft-pack-grid"><div><h3>Planned looks</h3>{draft.outfits.map(o=><label className="fft-check" key={o.id}><input type="checkbox" checked={o.packed} onChange={e=>change({outfits:draft.outfits.map(v=>v.id===o.id?{...v,packed:e.target.checked}:v)})}/><span><strong>{o.label}</strong><small>{o.items.join(' · ')}</small></span></label>)}{!draft.outfits.length&&<p className="fft-muted">Generate looks in the Outfits tab to make a checklist.</p>}</div><div><h3>From your closet</h3>{draft.closet.map(item=><div className="fft-pack-item" key={item.id}><span>✦</span>{item.name}<small>{item.category}</small></div>)}{!draft.closet.length&&<p className="fft-muted">Add items in the Outfits tab.</p>}</div></div><p className="fft-hint">Remember travel documents, medication, chargers, and weather-specific essentials.</p></div>}
    {tab==='inspo'&&<div className="fft-panel fft-wide"><span className="fft-kicker">06 / MOODBOARD</span><h2>Save the looks you love.</h2><p>Paste links from Pinterest or anywhere on the web. Your references stay with this trip.</p><div className="fft-add-row"><input aria-label="Inspiration URL" type="url" value={link} onChange={e=>setLink(e.target.value)} placeholder="https://www.pinterest.com/pin/…"/><button onClick={()=>{if(validInspiration(link)){change({inspiration:[...draft.inspiration,link]});setLink('')}else setMessage('Paste a valid web link.')}}>Save link</button></div><div className="fft-link-list">{draft.inspiration.map((url,i)=><div key={`${url}-${i}`}><a href={url} target="_blank" rel="noopener noreferrer">{new URL(url).hostname.replace('www.','')} ↗ <small>{url}</small></a><button aria-label="Remove inspiration link" onClick={()=>change({inspiration:draft.inspiration.filter((_,n)=>n!==i)})}>×</button></div>)}{!draft.inspiration.length&&<div className="fft-empty">A home for all your saved style ideas. ♡</div>}</div></div>}
    {tab==='shop'&&<div className="fft-panel fft-wide"><span className="fft-kicker">07 / THE FINISHING TOUCH</span><h2>Find the missing pieces.</h2><p>Browse India storefronts for ideas. Products and prices are set by each store. FitForTrip may earn a commission from selected shopping links, at no extra cost to you.</p><div className="fft-shop-grid">{shops.map(shop=><a key={shop.name} href={shop.url} target="_blank" rel="noopener noreferrer"><span>EXPLORE THE EDIT</span><strong>{shop.name}</strong><b>↗</b></a>)}</div><div className="fft-info"><strong>Shop your closet first.</strong><p>Review your outfit plan for gaps before buying anything new. Retailer product matching is coming in a later release.</p></div></div>}
    </section></div>}
  </main>
}
export default App;
