'use client';
import {useState, useEffect} from 'react';
import {submitWaitlist} from './waitlist';
import {Problem,HowItWorks,Destinations,Capsule,Shop,Features,Comparison,Packing,FinalCTA,Footer} from './sections';
const photo=(id:string,w=900)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=85`;
const paris=photo('photo-1600421693661-8a4accf2a899');
const outfit=photo('photo-1716004354593-95e48f5e9187');
function WaitlistForm(){const [state,setState]=useState('idle');const [message,setMessage]=useState('');return <form className="waitlist" onSubmit={async e=>{e.preventDefault();setState('loading');try{const result=await submitWaitlist(new FormData(e.currentTarget).get('email') as string);setMessage(result.demo?'Preview only — no email was stored.':'You’ll hear from us when early access opens.');setState('success')}catch(error){setMessage(error instanceof Error?error.message:'Something went wrong. Please try again.');setState('error')}}}>{state==='success'?<div className="success" role="status">You're on the list ✦ <small>{message}</small></div>:<><div className="email-row"><input aria-label="Email address" name="email" type="email" placeholder="Your email address" required disabled={state==='loading'}/><button disabled={state==='loading'}>{state==='loading'?'Saving your spot…':'Join the Waitlist'} <span>↗</span></button></div><small aria-live="polite">{state==='error'?message:'Be first in line for better-dressed trips. ✦'}</small></>}</form>}
function PhoneMockup(){return <div className="phone"><div className="phone-top"><span>9:41</span><b className="island"/><span>••• ▰</span></div><div className="phone-inner"><div className="phone-brand">FitForTrip <span>✦</span></div><p className="eyebrow">YOUR NEXT CHAPTER</p><h3>Bonjour, Paris.</h3><div className="phone-meta">12—17 OCT · 5 DAYS <span>☀ 17°</span></div><div className="phone-photo"><img src={outfit} alt="Chic neutral layers for a Paris city break"/><span>DAY 01 <b>City strolls & café stops</b></span><i>♡</i></div><div className="phone-bottom"><span>YOUR TRIP CAPSULE</span><strong>7 outfits. Zero overthinking.</strong><div>◉ &nbsp; My trip <span>♡ &nbsp; Closet</span><span>☷ &nbsp; Packing</span></div></div></div></div>}
function Hero(){return <section className="hero"><div className="hero-copy"><div className="pill">THE WELL-DRESSED WAY TO GET AWAY <span>✦ COMING SOON</span></div><h1>Never pack<br/>a <em>bad fit</em><br/>again<span className="period">.</span></h1><p>Your destination, weather, style and local trends — turned into outfits you'll actually want to wear.</p><WaitlistForm/><a className="text-link" href="#how-it-works">A little less packing panic. A lot more you. ↓</a></div><div className="hero-art"><div className="orbit"/><span className="big-star">✳</span><div className="polaroid paris"><img src={paris} alt="Eiffel Tower, Paris"/><span>Meet me in Paris ♡</span></div><div className="float-chip weather">☀ <b>PARIS · 17°C</b><small>A little layering weather.</small></div><PhoneMockup/><div className="float-chip style">✦ YOUR STYLE <b>Minimal + Chic</b></div><div className="float-chip capsule">✓ <b>7 outfits planned</b><small>One very happy suitcase.</small></div><div className="trip-stamp">FIT FOR<br/><em>the trip</em><br/>✦ EST. 2026 ✦</div><div className="art-caption">YOUR NEXT TRIP, BUT BETTER DRESSED.</div></div></section>}
export default function Home(){useEffect(()=>{const art=document.querySelector<HTMLElement>('.hero-art'); const move=(e:PointerEvent)=>{if(art&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches&&window.innerWidth>1000){art.style.translate=`${(e.clientX/window.innerWidth-.5)*9}px ${(e.clientY/window.innerHeight-.5)*7}px`}};window.addEventListener('pointermove',move); const scroll=()=>document.body.classList.toggle('scrolled',window.scrollY>40);window.addEventListener('scroll',scroll);return()=>{window.removeEventListener('scroll',scroll);window.removeEventListener('pointermove',move)}},[]);return <><nav className="navbar"><a className="wordmark" href="#">FitForTrip<span>✦</span></a><div className="navlinks"><a href="#how-it-works">How it works</a><a href="#features">Features</a><a href="#why">Why FitForTrip</a></div><a className="nav-cta" href="#waitlist">Join Waitlist <span>↗</span></a></nav><main><Hero/><Problem/><HowItWorks/><Destinations/><Capsule/><Shop/><Features/><Comparison/><Packing/><FinalCTA form={<WaitlistForm/>}/></main><Footer/></>}
